package com.dbzenith.world.arch;

import net.minecraft.world.level.material.MapColor;

import java.util.List;

/**
 * The landmark block set (CX-33). GENERATED by tools/gen_architecture.py from its BLOCKS table (with the textures,
 * models, blockstates, loot tables, tags and names): edit the table there and re-run, do not edit this file.
 */
public final class ArchitectureBlockList {
    public enum Shape { CUBE, CUBE_TB, PILLAR, GLASS, LAMP }

    public enum Material { STONE, HARD, CLAY, CLOTH, GLASS, LAMP, SAND, METAL }

    /** One block: its id, shape, material, map colour, and whether it has stairs, slab and wall variants. */
    public record Spec(String id, Shape shape, Material material, MapColor color, boolean stairs, boolean slab, boolean wall) {}

    public static final List<Spec> ALL = List.of(
            new Spec("tournament_stone", Shape.CUBE, Material.STONE, MapColor.SNOW, true, true, true),
            new Spec("tournament_tiles", Shape.CUBE, Material.STONE, MapColor.SNOW, true, true, false),
            new Spec("tournament_trim", Shape.CUBE_TB, Material.STONE, MapColor.SNOW, false, false, false),
            new Spec("tournament_red_band", Shape.CUBE, Material.STONE, MapColor.COLOR_RED, false, false, false),
            new Spec("arena_tile", Shape.CUBE, Material.STONE, MapColor.QUARTZ, true, true, false),
            new Spec("temple_plaster", Shape.CUBE, Material.STONE, MapColor.SAND, false, true, false),
            new Spec("temple_red_pillar", Shape.PILLAR, Material.STONE, MapColor.COLOR_RED, false, false, false),
            new Spec("temple_gold_trim", Shape.CUBE, Material.STONE, MapColor.COLOR_RED, false, false, false),
            new Spec("temple_gold", Shape.CUBE, Material.METAL, MapColor.GOLD, false, false, false),
            new Spec("clay_roof_tiles", Shape.CUBE, Material.CLAY, MapColor.TERRACOTTA_BROWN, true, true, false),
            new Spec("temple_lantern", Shape.LAMP, Material.LAMP, MapColor.COLOR_RED, false, false, false),
            new Spec("banner_cloth_red", Shape.CUBE, Material.CLOTH, MapColor.COLOR_RED, false, false, false),
            new Spec("banner_cloth_blue", Shape.CUBE, Material.CLOTH, MapColor.COLOR_BLUE, false, false, false),
            new Spec("banner_cloth_yellow", Shape.CUBE, Material.CLOTH, MapColor.COLOR_YELLOW, false, false, false),
            new Spec("banner_cloth_green", Shape.CUBE, Material.CLOTH, MapColor.COLOR_GREEN, false, false, false),
            new Spec("lookout_marble", Shape.CUBE, Material.STONE, MapColor.QUARTZ, true, true, true),
            new Spec("lookout_marble_pillar", Shape.PILLAR, Material.STONE, MapColor.QUARTZ, false, false, false),
            new Spec("lookout_deck_tiles", Shape.CUBE, Material.STONE, MapColor.QUARTZ, false, true, false),
            new Spec("lookout_gold_dome", Shape.CUBE, Material.METAL, MapColor.GOLD, true, true, false),
            new Spec("lookout_red_band", Shape.CUBE, Material.STONE, MapColor.COLOR_RED, false, false, false),
            new Spec("lookout_hull_white", Shape.CUBE, Material.STONE, MapColor.SNOW, false, false, false),
            new Spec("lookout_hull_window", Shape.LAMP, Material.LAMP, MapColor.COLOR_LIGHT_BLUE, false, false, false),
            new Spec("lookout_hull_trim", Shape.CUBE, Material.STONE, MapColor.SAND, false, false, false),
            new Spec("lookout_hull_teal", Shape.CUBE, Material.STONE, MapColor.COLOR_CYAN, false, false, false),
            new Spec("lookout_awning", Shape.CUBE, Material.CLOTH, MapColor.COLOR_PINK, true, true, false),
            new Spec("lookout_lamp", Shape.LAMP, Material.LAMP, MapColor.SNOW, false, false, false),
            new Spec("korin_stone", Shape.CUBE, Material.HARD, MapColor.STONE, true, true, true),
            new Spec("korin_bricks", Shape.CUBE, Material.HARD, MapColor.STONE, false, false, false),
            new Spec("korin_panel", Shape.CUBE, Material.HARD, MapColor.STONE, false, false, false),
            new Spec("cell_tile", Shape.CUBE, Material.STONE, MapColor.QUARTZ, true, true, false),
            new Spec("cell_spire", Shape.PILLAR, Material.STONE, MapColor.QUARTZ, false, false, false),
            new Spec("cell_spire_cap", Shape.CUBE, Material.STONE, MapColor.QUARTZ, false, false, true),
            new Spec("wasteland_rock", Shape.CUBE, Material.STONE, MapColor.TERRACOTTA_LIGHT_GRAY, true, true, false),
            new Spec("strata_red", Shape.CUBE, Material.STONE, MapColor.TERRACOTTA_RED, true, true, false),
            new Spec("strata_brown", Shape.CUBE, Material.STONE, MapColor.TERRACOTTA_BROWN, true, true, false),
            new Spec("strata_tan", Shape.CUBE, Material.STONE, MapColor.TERRACOTTA_ORANGE, true, true, false),
            new Spec("strata_cream", Shape.CUBE, Material.STONE, MapColor.TERRACOTTA_WHITE, true, true, false),
            new Spec("frypan_sand", Shape.CUBE, Material.SAND, MapColor.SAND, false, false, false),
            new Spec("city_concrete", Shape.CUBE, Material.STONE, MapColor.SNOW, true, true, true),
            new Spec("city_window", Shape.LAMP, Material.GLASS, MapColor.COLOR_LIGHT_BLUE, false, false, false),
            new Spec("city_glass", Shape.GLASS, Material.GLASS, MapColor.COLOR_LIGHT_BLUE, false, false, false),
            new Spec("city_roof_red", Shape.CUBE, Material.CLAY, MapColor.COLOR_RED, true, true, false),
            new Spec("city_roof_orange", Shape.CUBE, Material.CLAY, MapColor.COLOR_ORANGE, true, true, false),
            new Spec("city_road", Shape.CUBE, Material.STONE, MapColor.COLOR_GRAY, false, true, false),
            new Spec("city_road_line", Shape.CUBE, Material.STONE, MapColor.COLOR_GRAY, false, false, false),
            new Spec("city_sidewalk", Shape.CUBE, Material.STONE, MapColor.COLOR_LIGHT_GRAY, false, true, false),
            new Spec("city_streetlamp", Shape.LAMP, Material.LAMP, MapColor.SNOW, false, false, false),
            new Spec("city_pier_deck", Shape.CUBE, Material.CLAY, MapColor.WOOD, false, true, false));

    private ArchitectureBlockList() {}
}
